version: "3.9"
services:
  api:
    container_name: fastify-api
    build:
      context: .
      dockerfile: Dockerfile
    image: fastify-api 
    restart: always
    ports:
      - "3001:${SERVER_PORT}"  
    links: 
      - appDb 
  appDb:
    container_name: appDb
    image: mysql:latest
    restart: always
    environment: 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:${DB_PORT}"
